-- إصلاح جدول المعقبين وصلاحيات الأمان
-- 1. إنشاء الجدول بأنواع بيانات متوافقة مع التطبيق (BigInt)
CREATE TABLE IF NOT EXISTS "public"."agents" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "user_id" BIGINT NOT NULL,
    "name" TEXT NOT NULL,
    "phone" TEXT,
    "whatsapp" TEXT,
    "created_at" TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 2. تفعيل الحماية
ALTER TABLE "public"."agents" ENABLE ROW LEVEL SECURITY;

-- 3. تنظيف السياسات القديمة
DROP POLICY IF EXISTS "Enable insert for app" ON "public"."agents";
DROP POLICY IF EXISTS "Enable select for app" ON "public"."agents";
DROP POLICY IF EXISTS "Enable delete for app" ON "public"."agents";

-- 4. إنشاء سياسات مرنة لنظام الدخول المخصص
CREATE POLICY "Enable insert for app" ON "public"."agents"
FOR INSERT TO anon, authenticated WITH CHECK (true);

CREATE POLICY "Enable select for app" ON "public"."agents"
FOR SELECT TO anon, authenticated USING (true);

CREATE POLICY "Enable delete for app" ON "public"."agents"
FOR DELETE TO anon, authenticated USING (true);
