-- 1. إنشاء جدول المعقبين (agents)
-- الهيكل مطابق لبيانات المعقب في التطبيق مع إضافة user_id للربط
CREATE TABLE IF NOT EXISTS "public"."agents" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "user_id" BIGINT NOT NULL, -- لربط المعقب بالمستخدم (المكتب)
    "name" TEXT NOT NULL,
    "phone" TEXT,
    "whatsapp" TEXT,
    "created_at_ms" BIGINT NOT NULL, -- لتخزين createdAt (رقم) القادم من التطبيق
    "created_at" TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 2. تفعيل نظام الحماية (Row Level Security)
ALTER TABLE "public"."agents" ENABLE ROW LEVEL SECURITY;

-- 3. حذف السياسات القديمة لتجنب التعارض
DROP POLICY IF EXISTS "Enable insert for app" ON "public"."agents";
DROP POLICY IF EXISTS "Enable select for app" ON "public"."agents";
DROP POLICY IF EXISTS "Enable delete for app" ON "public"."agents";
DROP POLICY IF EXISTS "Enable update for app" ON "public"."agents";

-- 4. إنشاء سياسات تسمح للموقع بالكتابة والقراءة (نسخة طبق الأصل من المصروفات)
-- هذه السياسات تسمح للـ Anon (الموقع) بالتعامل مع الجدول، ويتم فلترة البيانات لاحقاً بالكود عبر user_id

CREATE POLICY "Enable insert for app" ON "public"."agents"
FOR INSERT TO anon, authenticated WITH CHECK (true);

CREATE POLICY "Enable select for app" ON "public"."agents"
FOR SELECT TO anon, authenticated USING (true);

CREATE POLICY "Enable delete for app" ON "public"."agents"
FOR DELETE TO anon, authenticated USING (true);

CREATE POLICY "Enable update for app" ON "public"."agents"
FOR UPDATE TO anon, authenticated USING (true);
