-- 1. إنشاء جدول المستخدمين (users)
-- يطابق واجهة التسجيل: اسم المكتب، الجوال، كلمة المرور، أسئلة الأمان
CREATE TABLE IF NOT EXISTS public.users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, -- المعرف الفريد
    office_name TEXT NOT NULL,                              -- يقابل: officeName (اسم المكتب)
    phone TEXT NOT NULL UNIQUE,                             -- يقابل: phone (رقم الجوال - ممنوع التكرار)
    password_hash TEXT NOT NULL,                            -- يقابل: passwordHash (كلمة المرور المشفرة)
    security_question TEXT NOT NULL,                        -- يقابل: securityQuestion (سؤال الأمان)
    security_answer TEXT NOT NULL,                          -- يقابل: securityAnswer (إجابة السؤال)
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()       -- يقابل: createdAt (تاريخ ووقت التسجيل)
);

-- 2. إضافة تعليقات للأعمدة (اختياري للتوضيح)
COMMENT ON TABLE public.users IS 'جدول بيانات المكاتب المسجلة في النظام';
COMMENT ON COLUMN public.users.office_name IS 'اسم المكتب الظاهر في الواجهة';
COMMENT ON COLUMN public.users.phone IS 'رقم الجوال المستخدم للدخول';

-- 3. إعدادات الأمان (Row Level Security) - في حال استخدام Supabase
-- تفعيل الأمان على الجدول
ALTER TABLE public.users ENABLE ROW LEVEL SECURITY;

-- السماح لأي شخص بإنشاء حساب جديد (Insert)
CREATE POLICY "Allow public registration" 
ON public.users 
FOR INSERT 
TO anon, authenticated 
WITH CHECK (true);

-- السماح للمستخدمين بقراءة بياناتهم فقط بناءً على رقم الجوال (مثال بسيط)
-- ملاحظة: في الأنظمة المتقدمة يفضل استخدام Supabase Auth ID
CREATE POLICY "Allow users to read own data" 
ON public.users 
FOR SELECT 
USING (true);
